/**
 * glossary.ts — field dictionary for tw-lvr output.
 *
 * Consumed by `tw-lvr glossary` and `tw-lvr schema`. `official` means the
 * underlying concept/label aligns with the government LVR field vocabulary.
 * `origin` tells users how this CLI output value is produced.
 */

export type FieldLayer = "clean" | "refined";
export type FieldOrigin = "site" | "normalized" | "parsed" | "computed" | "inferred" | "metadata";

export interface GlossaryEntry {
  /** Output JSON key. */
  field: string;
  /** Short human label (zh/en). */
  label: string;
  /** Unit, or "" if not a measured quantity. */
  unit: string;
  /** One-line definition. */
  definition: string;
  /** Formula or derivation note for non-trivial computed/parsed fields. */
  formula?: string;
  /** "clean" = always present; "refined" = only with --refine. */
  layer: FieldLayer;
  /** How this CLI output value is produced. */
  origin: FieldOrigin;
  /** true if the field concept/label aligns with 內政部 official LVR vocabulary. */
  official: boolean;
}

export const GLOSSARY: GlossaryEntry[] = [
  // Layer A: Clean Raw Record (faithful to source; no analytical judgement).
  {
    field: "building",
    label: "社區/建物名稱 (community/building)",
    unit: "",
    definition: "Community/building name from the site's `bn` field; empty string if unknown.",
    layer: "clean",
    origin: "site",
    official: false,
  },
  {
    field: "buildingUnit",
    label: "棟戶/戶別 (building unit)",
    unit: "",
    definition: "Presale/building unit label from the site's `bu` field, e.g. `A2棟0號`; empty when the live row does not provide it.",
    layer: "clean",
    origin: "site",
    official: false,
  },
  {
    field: "address",
    label: "地址 (door address)",
    unit: "",
    definition: "Human-readable transaction address normalized to half-width digits.",
    formula: "Parsed from raw `a`; if `a` contains '#', uses the human-readable side after '#'.",
    layer: "clean",
    origin: "parsed",
    official: false,
  },
  {
    field: "addrNum",
    label: "門牌號 (door number)",
    unit: "",
    definition: "Door number only, parsed from `address`.",
    formula: "First number-like segment before `號`, after full-width digit normalization.",
    layer: "clean",
    origin: "parsed",
    official: false,
  },
  {
    field: "txnDate",
    label: "交易年月 (txn month)",
    unit: "",
    definition: "Transaction month in western calendar.",
    formula: "ROC year in `txnDateRoc` + 1911, keeping the source month.",
    layer: "clean",
    origin: "computed",
    official: false,
  },
  {
    field: "txnDateRoc",
    label: "交易日期 (ROC)",
    unit: "",
    definition: "Raw transaction date in ROC calendar, `YYY/MM/DD`; newest-first sorting uses this field.",
    layer: "clean",
    origin: "site",
    official: true,
  },
  {
    field: "totalPriceWan",
    label: "交易總價 (total price)",
    unit: "萬元",
    definition: "Total transaction price, possibly including parking.",
    formula: "Raw site `tp` in TWD / 10,000.",
    layer: "clean",
    origin: "normalized",
    official: true,
  },
  {
    field: "rawUnitPrice",
    label: "原始單價 (raw unit price)",
    unit: "萬元/坪",
    definition: "Back-calculated raw unit price with parking still bundled; not ideal for comparable-price analysis.",
    formula: "totalPriceWan / totalAreaPing.",
    layer: "clean",
    origin: "computed",
    official: false,
  },
  {
    field: "siteAdjUnitPrice",
    label: "交易單價 (site unit price)",
    unit: "萬元/坪",
    definition: "Unit price exactly as reported by the live site. Despite the legacy field name, this can be parking-deducted or parking-included; inspect `siteUnitPriceFormula`.",
    formula: "Raw site `p` in TWD/ping / 10,000.",
    layer: "clean",
    origin: "normalized",
    official: true,
  },
  {
    field: "siteUnitPriceFormula",
    label: "單價公式 (site unit-price formula)",
    unit: "",
    definition: "Raw site formula text explaining the displayed unit-price basis.",
    formula: "`(總價-車位總價)/(總面積-車位總面積)` means parking-deducted; `總價/總面積` means parking-included/plain total-area.",
    layer: "clean",
    origin: "site",
    official: false,
  },
  {
    field: "totalAreaPing",
    label: "建物移轉總面積 (total area, ping)",
    unit: "坪",
    definition: "Total transferred floor area in ping.",
    layer: "clean",
    origin: "site",
    official: true,
  },
  {
    field: "totalAreaM2",
    label: "建物移轉總面積 (total area, m2)",
    unit: "m2",
    definition: "Total transferred floor area expressed in square metres.",
    formula: "totalAreaPing * 3.30579.",
    layer: "clean",
    origin: "computed",
    official: true,
  },
  {
    field: "mainBuildingPct",
    label: "主建物佔比 (main building share)",
    unit: "%",
    definition: "Main-building area as a percentage of total transferred area.",
    formula: "Parsed from raw site `bs`, e.g. `46.27%` -> 46.27.",
    layer: "clean",
    origin: "parsed",
    official: true,
  },
  {
    field: "mainAreaM2",
    label: "主建物面積 (main area, m2)",
    unit: "m2",
    definition: "Main-building area in square metres.",
    formula: "totalAreaM2 * mainBuildingPct / 100 when percentage is available.",
    layer: "clean",
    origin: "computed",
    official: true,
  },
  {
    field: "parkPriceWan",
    label: "車位總價 (parking price)",
    unit: "萬元",
    definition: "Reported parking price. Zero does not necessarily mean no parking.",
    formula: "Raw site `cp` / 10,000-equivalent display value.",
    layer: "clean",
    origin: "normalized",
    official: true,
  },
  {
    field: "parkAreaM2",
    label: "車位面積 (parking area, m2)",
    unit: "m2",
    definition: "Parking area if available; currently null on list-form live rows.",
    layer: "clean",
    origin: "site",
    official: true,
  },
  {
    field: "parkCount",
    label: "車位數 (parking count)",
    unit: "count",
    definition: "Best-effort parking-space count parsed from transaction subject text.",
    formula: "0 when `txnType` has no 車位; explicit 車位N when present; otherwise 1 if 車位 appears.",
    layer: "clean",
    origin: "parsed",
    official: false,
  },
  {
    field: "txnType",
    label: "交易標的 (txn subject)",
    unit: "",
    definition: "What the transaction covered, e.g. 房地(土地+建物)+車位.",
    layer: "clean",
    origin: "site",
    official: true,
  },
  {
    field: "floor",
    label: "樓別/樓高 (floor)",
    unit: "",
    definition: "Transferred floor / total floors.",
    layer: "clean",
    origin: "site",
    official: true,
  },
  {
    field: "buildingType",
    label: "建物型態 (building type)",
    unit: "",
    definition: "Building type, e.g. 住宅大樓、公寓、套房.",
    layer: "clean",
    origin: "site",
    official: true,
  },
  {
    field: "mainUse",
    label: "主要用途 (main use)",
    unit: "",
    definition: "Main use, e.g. 住家用.",
    layer: "clean",
    origin: "site",
    official: true,
  },
  {
    field: "layout",
    label: "格局 (layout)",
    unit: "",
    definition: "Building layout, e.g. 3房2廳2衛.",
    layer: "clean",
    origin: "site",
    official: true,
  },
  {
    field: "hasElevator",
    label: "電梯 (elevator)",
    unit: "boolean",
    definition: "Whether the building has an elevator.",
    formula: "Raw site `el` value `有` -> true; otherwise false.",
    layer: "clean",
    origin: "parsed",
    official: true,
  },
  {
    field: "note",
    label: "備註 (note)",
    unit: "",
    definition: "Registry note text; exclusion signals often appear here.",
    layer: "clean",
    origin: "site",
    official: true,
  },
  {
    field: "lat",
    label: "緯度 (latitude)",
    unit: "degrees",
    definition: "Latitude from the live site response.",
    layer: "clean",
    origin: "site",
    official: false,
  },
  {
    field: "lon",
    label: "經度 (longitude)",
    unit: "degrees",
    definition: "Longitude from the live site response.",
    layer: "clean",
    origin: "site",
    official: false,
  },
  {
    field: "detailKey",
    label: "明細鍵 (detail key)",
    unit: "",
    definition: "Opaque site key (`sq`) for the per-row detail record.",
    layer: "clean",
    origin: "site",
    official: false,
  },
  {
    field: "meta",
    label: "後設資料 (meta)",
    unit: "",
    definition: "CLI/library provenance object; omitted from CSV output.",
    formula: "{ fetchedAt, queryId? } generated by this pipeline.",
    layer: "clean",
    origin: "metadata",
    official: false,
  },

  // Layer B: Refined Record (only with --refine; adds judgement/provenance).
  {
    field: "netPriceWan",
    label: "淨房地價 (net price)",
    unit: "萬元",
    definition: "Price numerator after subtracting separately reported parking price. If parking price is bundled/unreported, the numerator stays as totalPriceWan.",
    formula: "parkPriceSource=reported: totalPriceWan - parkPriceWan; included_in_total/none: totalPriceWan.",
    layer: "refined",
    origin: "computed",
    official: false,
  },
  {
    field: "netAreaPing",
    label: "淨面積 (net area)",
    unit: "坪",
    definition: "Area with reported/inferred parking area removed.",
    formula: "totalAreaPing - parkAreaM2 / 3.30579, or implied from siteAdjUnitPrice when available.",
    layer: "refined",
    origin: "computed",
    official: false,
  },
  {
    field: "adjUnitPrice",
    label: "校正單價(扣車位) (adjusted unit price)",
    unit: "萬元/坪",
    definition: "Pipeline's comparable unit-price field. On live rows it mirrors the site's displayed unit price when present; inspect `siteUnitPriceFormula` to know whether the site deducted parking.",
    formula: "Uses siteAdjUnitPrice when present; otherwise netPriceWan / netAreaPing.",
    layer: "refined",
    origin: "computed",
    official: false,
  },
  {
    field: "excluded",
    label: "建議排除 (excluded)",
    unit: "boolean",
    definition: "true when the row should be dropped from comparable-price analysis.",
    formula: "Derived from excludeReason: kinship, pure parking, or non-residential use.",
    layer: "refined",
    origin: "inferred",
    official: false,
  },
  {
    field: "excludeReason",
    label: "排除原因 (exclude reason)",
    unit: "",
    definition: "Reason for exclusion, or empty string when not excluded.",
    formula: "親友交易 from note; 純車位 from price/subject; 非住宅 from mainUse.",
    layer: "refined",
    origin: "inferred",
    official: false,
  },
  {
    field: "isPresale",
    label: "預售屋 (presale)",
    unit: "boolean",
    definition: "true if note text indicates a pre-sale transaction.",
    formula: "Looks for 預售 in `note`.",
    layer: "refined",
    origin: "inferred",
    official: false,
  },
  {
    field: "parkPriceIncluded",
    label: "車位價內含 (park price included)",
    unit: "boolean",
    definition: "true when parking exists but no separate parking price is reported.",
    formula: "parkCount > 0 and parkPriceWan is 0; no invented parking price is subtracted.",
    layer: "refined",
    origin: "inferred",
    official: false,
  },
  {
    field: "parkPriceSource",
    label: "車位價格來源 (parking price source)",
    unit: "",
    definition: "Provenance for the price subtraction side of adjusted calculations.",
    formula: "none | reported | included_in_total.",
    layer: "refined",
    origin: "inferred",
    official: false,
  },
  {
    field: "parkAreaUnreported",
    label: "車位面積未揭露(推估) (park area unreported)",
    unit: "boolean",
    definition: "true when parking exists but parking area is missing.",
    formula: "parkCount > 0 and parkAreaM2 is null.",
    layer: "refined",
    origin: "inferred",
    official: false,
  },
  {
    field: "parkingRefSource",
    label: "車位推估來源 (parking ref source)",
    unit: "",
    definition: "Basis used for parking-area adjustment.",
    formula: "reported | derived | district_fallback | curated.",
    layer: "refined",
    origin: "metadata",
    official: false,
  },
  {
    field: "confidence",
    label: "信心度 (confidence)",
    unit: "",
    definition: "Rollup confidence in adjusted figures; not an independent valuation model.",
    formula: "high | medium | low, degraded by exclusions and inferred parking inputs.",
    layer: "refined",
    origin: "inferred",
    official: false,
  },
];

/** All clean-layer field names, in declaration order. */
export const CLEAN_FIELDS: string[] = GLOSSARY.filter((g) => g.layer === "clean").map((g) => g.field);

/** All refined-layer field names, in declaration order. */
export const REFINED_FIELDS: string[] = GLOSSARY.filter((g) => g.layer === "refined").map((g) => g.field);
