/**
 * glossary.ts — field dictionary for tw-lvr output.
 *
 * Consumed by `tw-lvr glossary` and `tw-lvr schema`. `official` means the
 * underlying concept/label aligns with the government LVR field vocabulary.
 * `origin` tells users how this CLI output value is produced.
 */

export type FieldLayer = "clean" | "refined" | "rent-clean" | "rent-refined";
export type FieldOrigin = "site" | "normalized" | "parsed" | "computed" | "inferred" | "metadata";

export interface GlossaryEntry {
  /** Output JSON key. */
  field: string;
  /** Short human label (zh/en). */
  label: string;
  /** Unit, or "" if not a measured quantity. */
  unit: string;
  /** One-line definition. */
  definition: string;
  /** Formula or derivation note for non-trivial computed/parsed fields. */
  formula?: string;
  /** "clean" = always present; "refined" = only with --refine. */
  layer: FieldLayer;
  /** How this CLI output value is produced. */
  origin: FieldOrigin;
  /** true if the field concept/label aligns with 內政部 official LVR vocabulary. */
  official: boolean;
}

export const GLOSSARY: GlossaryEntry[] = [
  // Layer A: Clean Raw Record (faithful to source; no analytical judgement).
  {
    field: "building",
    label: "社區/建物名稱 (community/building)",
    unit: "",
    definition: "Community/building name from the site's `bn` field; empty string if unknown.",
    layer: "clean",
    origin: "site",
    official: false,
  },
  {
    field: "buildingUnit",
    label: "棟戶/戶別 (building unit)",
    unit: "",
    definition: "Presale/building unit label from the site's `bu` field, e.g. `A2棟0號`; empty when the live row does not provide it.",
    layer: "clean",
    origin: "site",
    official: false,
  },
  {
    field: "address",
    label: "地址 (door address)",
    unit: "",
    definition: "Human-readable transaction address normalized to half-width digits.",
    formula: "Parsed from raw `a`; if `a` contains '#', uses the human-readable side after '#'.",
    layer: "clean",
    origin: "parsed",
    official: false,
  },
  {
    field: "addrNum",
    label: "門牌號 (door number)",
    unit: "",
    definition: "Door number only, parsed from `address`.",
    formula: "First number-like segment before `號`, after full-width digit normalization.",
    layer: "clean",
    origin: "parsed",
    official: false,
  },
  {
    field: "txnDate",
    label: "交易年月 (txn month)",
    unit: "",
    definition: "Transaction month in western calendar.",
    formula: "ROC year in `txnDateRoc` + 1911, keeping the source month.",
    layer: "clean",
    origin: "computed",
    official: false,
  },
  {
    field: "txnDateRoc",
    label: "交易日期 (ROC)",
    unit: "",
    definition: "Raw transaction date in ROC calendar, `YYY/MM/DD`; newest-first sorting uses this field.",
    layer: "clean",
    origin: "site",
    official: true,
  },
  {
    field: "totalPriceWan",
    label: "交易總價 (total price)",
    unit: "萬元",
    definition: "Total transaction price, possibly including parking.",
    formula: "Raw site `tp` in TWD / 10,000.",
    layer: "clean",
    origin: "normalized",
    official: true,
  },
  {
    field: "rawUnitPrice",
    label: "原始單價 (raw unit price)",
    unit: "萬元/坪",
    definition: "Back-calculated raw unit price with parking still bundled; not ideal for comparable-price analysis.",
    formula: "totalPriceWan / totalAreaPing.",
    layer: "clean",
    origin: "computed",
    official: false,
  },
  {
    field: "siteAdjUnitPrice",
    label: "交易單價 (site unit price)",
    unit: "萬元/坪",
    definition: "Unit price exactly as reported by the live site. Despite the legacy field name, this can be parking-deducted or parking-included; inspect `siteUnitPriceFormula`.",
    formula: "Raw site `p` in TWD/ping / 10,000.",
    layer: "clean",
    origin: "normalized",
    official: true,
  },
  {
    field: "siteUnitPriceFormula",
    label: "單價公式 (site unit-price formula)",
    unit: "",
    definition: "Raw site formula text explaining the displayed unit-price basis.",
    formula: "`(總價-車位總價)/(總面積-車位總面積)` means parking-deducted; `總價/總面積` means parking-included/plain total-area.",
    layer: "clean",
    origin: "site",
    official: false,
  },
  {
    field: "totalAreaPing",
    label: "建物移轉總面積 (total area, ping)",
    unit: "坪",
    definition: "Total transferred floor area in ping.",
    layer: "clean",
    origin: "site",
    official: true,
  },
  {
    field: "totalAreaM2",
    label: "建物移轉總面積 (total area, m2)",
    unit: "m2",
    definition: "Total transferred floor area expressed in square metres.",
    formula: "totalAreaPing * 3.30579.",
    layer: "clean",
    origin: "computed",
    official: true,
  },
  {
    field: "mainBuildingPct",
    label: "主建物佔比 (main building share)",
    unit: "%",
    definition: "Main-building area as a percentage of total transferred area.",
    formula: "Parsed from raw site `bs`, e.g. `46.27%` -> 46.27.",
    layer: "clean",
    origin: "parsed",
    official: true,
  },
  {
    field: "mainAreaM2",
    label: "主建物面積 (main area, m2)",
    unit: "m2",
    definition: "Main-building area in square metres.",
    formula: "totalAreaM2 * mainBuildingPct / 100 when percentage is available.",
    layer: "clean",
    origin: "computed",
    official: true,
  },
  {
    field: "parkPriceWan",
    label: "車位總價 (parking price)",
    unit: "萬元",
    definition: "Reported parking price. Zero does not necessarily mean no parking.",
    formula: "Raw site `cp` / 10,000-equivalent display value.",
    layer: "clean",
    origin: "normalized",
    official: true,
  },
  {
    field: "parkAreaM2",
    label: "車位面積 (parking area, m2)",
    unit: "m2",
    definition: "Parking area if available; currently null on list-form live rows.",
    layer: "clean",
    origin: "site",
    official: true,
  },
  {
    field: "parkCount",
    label: "車位數 (parking count)",
    unit: "count",
    definition: "Best-effort parking-space count parsed from transaction subject text.",
    formula: "0 when `txnType` has no 車位; explicit 車位N when present; otherwise 1 if 車位 appears.",
    layer: "clean",
    origin: "parsed",
    official: false,
  },
  {
    field: "txnType",
    label: "交易標的 (txn subject)",
    unit: "",
    definition: "What the transaction covered, e.g. 房地(土地+建物)+車位.",
    layer: "clean",
    origin: "site",
    official: true,
  },
  {
    field: "floor",
    label: "樓別/樓高 (floor)",
    unit: "",
    definition: "Transferred floor / total floors.",
    layer: "clean",
    origin: "site",
    official: true,
  },
  {
    field: "buildingType",
    label: "建物型態 (building type)",
    unit: "",
    definition: "Building type, e.g. 住宅大樓、公寓、套房.",
    layer: "clean",
    origin: "site",
    official: true,
  },
  {
    field: "mainUse",
    label: "主要用途 (main use)",
    unit: "",
    definition: "Main use, e.g. 住家用.",
    layer: "clean",
    origin: "site",
    official: true,
  },
  {
    field: "layout",
    label: "格局 (layout)",
    unit: "",
    definition: "Building layout, e.g. 3房2廳2衛.",
    layer: "clean",
    origin: "site",
    official: true,
  },
  {
    field: "hasElevator",
    label: "電梯 (elevator)",
    unit: "boolean",
    definition: "Whether the building has an elevator.",
    formula: "Raw site `el` value `有` -> true; otherwise false.",
    layer: "clean",
    origin: "parsed",
    official: true,
  },
  {
    field: "note",
    label: "備註 (note)",
    unit: "",
    definition: "Registry note text; exclusion signals often appear here.",
    layer: "clean",
    origin: "site",
    official: true,
  },
  {
    field: "lat",
    label: "緯度 (latitude)",
    unit: "degrees",
    definition: "Latitude from the live site response.",
    layer: "clean",
    origin: "site",
    official: false,
  },
  {
    field: "lon",
    label: "經度 (longitude)",
    unit: "degrees",
    definition: "Longitude from the live site response.",
    layer: "clean",
    origin: "site",
    official: false,
  },
  {
    field: "detailKey",
    label: "明細鍵 (detail key)",
    unit: "",
    definition: "Opaque site key (`sq`) for the per-row detail record.",
    layer: "clean",
    origin: "site",
    official: false,
  },
  {
    field: "meta",
    label: "後設資料 (meta)",
    unit: "",
    definition: "CLI/library provenance object; omitted from CSV output.",
    formula: "{ fetchedAt, queryId? } generated by this pipeline.",
    layer: "clean",
    origin: "metadata",
    official: false,
  },

  // Layer B: Refined Record (only with --refine; adds judgement/provenance).
  {
    field: "netPriceWan",
    label: "淨房地價 (net price)",
    unit: "萬元",
    definition: "Price numerator after subtracting separately reported parking price. If parking price is bundled/unreported, the numerator stays as totalPriceWan.",
    formula: "parkPriceSource=reported: totalPriceWan - parkPriceWan; included_in_total/none: totalPriceWan.",
    layer: "refined",
    origin: "computed",
    official: false,
  },
  {
    field: "netAreaPing",
    label: "淨面積 (net area)",
    unit: "坪",
    definition: "Area with reported/inferred parking area removed.",
    formula: "totalAreaPing - parkAreaM2 / 3.30579, or implied from siteAdjUnitPrice when available.",
    layer: "refined",
    origin: "computed",
    official: false,
  },
  {
    field: "adjUnitPrice",
    label: "校正單價(扣車位) (adjusted unit price)",
    unit: "萬元/坪",
    definition: "Pipeline's comparable unit-price field. On live rows it mirrors the site's displayed unit price when present; inspect `siteUnitPriceFormula` to know whether the site deducted parking.",
    formula: "Uses siteAdjUnitPrice when present; otherwise netPriceWan / netAreaPing.",
    layer: "refined",
    origin: "computed",
    official: false,
  },
  {
    field: "excluded",
    label: "建議排除 (excluded)",
    unit: "boolean",
    definition: "true when the row should be dropped from comparable-price analysis.",
    formula: "Derived from excludeReason: kinship, pure parking, or non-residential use.",
    layer: "refined",
    origin: "inferred",
    official: false,
  },
  {
    field: "excludeReason",
    label: "排除原因 (exclude reason)",
    unit: "",
    definition: "Reason for exclusion, or empty string when not excluded.",
    formula: "親友交易 from note; 純車位 from price/subject; 非住宅 from mainUse.",
    layer: "refined",
    origin: "inferred",
    official: false,
  },
  {
    field: "isPresale",
    label: "預售屋 (presale)",
    unit: "boolean",
    definition: "true if note text indicates a pre-sale transaction.",
    formula: "Looks for 預售 in `note`.",
    layer: "refined",
    origin: "inferred",
    official: false,
  },
  {
    field: "parkPriceIncluded",
    label: "車位價內含 (park price included)",
    unit: "boolean",
    definition: "true when parking exists but no separate parking price is reported.",
    formula: "parkCount > 0 and parkPriceWan is 0; no invented parking price is subtracted.",
    layer: "refined",
    origin: "inferred",
    official: false,
  },
  {
    field: "parkPriceSource",
    label: "車位價格來源 (parking price source)",
    unit: "",
    definition: "Provenance for the price subtraction side of adjusted calculations.",
    formula: "none | reported | included_in_total.",
    layer: "refined",
    origin: "inferred",
    official: false,
  },
  {
    field: "parkAreaUnreported",
    label: "車位面積未揭露(推估) (park area unreported)",
    unit: "boolean",
    definition: "true when parking exists but parking area is missing.",
    formula: "parkCount > 0 and parkAreaM2 is null.",
    layer: "refined",
    origin: "inferred",
    official: false,
  },
  {
    field: "parkingRefSource",
    label: "車位推估來源 (parking ref source)",
    unit: "",
    definition: "Basis used for parking-area adjustment.",
    formula: "reported | derived | district_fallback | curated.",
    layer: "refined",
    origin: "metadata",
    official: false,
  },
  {
    field: "confidence",
    label: "信心度 (confidence)",
    unit: "",
    definition: "Rollup confidence in adjusted figures; not an independent valuation model.",
    formula: "high | medium | low, degraded by exclusions and inferred parking inputs.",
    layer: "refined",
    origin: "inferred",
    official: false,
  },

  // ── RENT (租賃) — Clean Rent Record (--rent). Faithful to source. ──────────
  { field: "building", label: "社區名 (community)", unit: "", definition: "Community name from rent `bn`; empty if none.", layer: "rent-clean", origin: "site", official: false },
  { field: "address", label: "地址 (address)", unit: "", definition: "Lease address, half-width digits; land rows carry 地號.", formula: "Parsed from raw `a` (human side after '#').", layer: "rent-clean", origin: "parsed", official: false },
  { field: "addrNum", label: "門牌號 (door number)", unit: "", definition: "Door number only; '' for land 地號 rows.", formula: "Digits immediately before 號 in the address.", layer: "rent-clean", origin: "parsed", official: false },
  { field: "txnDate", label: "簽約年月 (lease month)", unit: "", definition: "Contract month, western YYYY-MM.", formula: "ROC `e` + 1911.", layer: "rent-clean", origin: "normalized", official: true },
  { field: "txnDateRoc", label: "簽約日 (ROC date)", unit: "", definition: "Raw ROC contract date, e.g. 112/08/01.", layer: "rent-clean", origin: "site", official: true },
  { field: "monthlyRentTwd", label: "月租金 (monthly rent)", unit: "TWD/月", definition: "Total monthly rent (租金總額), parking still inside. NOTE: 元, not 萬.", formula: "Raw `tp`, comma-stripped.", layer: "rent-clean", origin: "site", official: true },
  { field: "unitRentTwdPing", label: "單價 (unit rent)", unit: "TWD/坪/月", definition: "Site-reported rent per 坪 per month; falls back to raw when the site omits it. HEADLINE field for residential rent comps (median over non-excluded rows; ≈ adjUnitRentTwdPing for most residential leases).", formula: "Raw `p`; else 月租金/面積.", layer: "rent-clean", origin: "site", official: true },
  { field: "unitRentFormula", label: "單價公式 (unit-rent formula)", unit: "", definition: "The site's basis for unitRentTwdPing.", formula: "Raw `msg`, e.g. 總價/總面積.", layer: "rent-clean", origin: "site", official: true },
  { field: "rawUnitRentTwdPing", label: "原始單價 (raw unit rent)", unit: "TWD/坪/月", definition: "True raw rent per 坪 (parking still inside).", formula: "月租金 / 面積.", layer: "rent-clean", origin: "computed", official: false },
  { field: "areaPing", label: "面積 (area)", unit: "坪", definition: "Leased floor area in 坪.", formula: "Raw `s`.", layer: "rent-clean", origin: "site", official: true },
  { field: "areaM2", label: "面積 (area)", unit: "m²", definition: "Leased area in square metres.", formula: "面積(坪) × 3.30579.", layer: "rent-clean", origin: "computed", official: false },
  { field: "parkRentTwd", label: "車位租金 (parking rent)", unit: "TWD/月", definition: "Separately reported car-park rent; 0 if none/bundled.", formula: "Raw `cp`.", layer: "rent-clean", origin: "site", official: true },
  { field: "rentTarget", label: "租賃標的 (lease target)", unit: "", definition: "Old form (簽約 ≤112/08): 建物 / 房地(土地+建物)(+車位) / 車位 / 土地. New form (≥112/09): 租賃房屋 / 租賃房屋+車位.", formula: "Raw `t`.", layer: "rent-clean", origin: "site", official: true },
  { field: "buildingType", label: "建物型態 (building type)", unit: "", definition: "住宅大樓/華廈/公寓/店面/套房/… ; '' for land.", formula: "Raw `b`.", layer: "rent-clean", origin: "site", official: true },
  { field: "mainUse", label: "主要用途 (main use)", unit: "", definition: "住家用/商業用/…", formula: "Raw `pu`.", layer: "rent-clean", origin: "site", official: true },
  { field: "useClass", label: "用途類別/使用分區 (zoning class)", unit: "", definition: "住 / 商 / 其他 — the site's zoning-derived filter bucket, NOT the lease's actual use (信義計畫區-style 特定專用區 luxury towers land in 其他). Never filter residential on this; use mainUse via `excluded`. Empty on ~94% of new-form rows (簽約 ≥112/09) — effectively an old-form-only field.", formula: "Raw `AA11`.", layer: "rent-clean", origin: "site", official: true },
  { field: "layout", label: "格局 (layout)", unit: "", definition: "Room layout, e.g. 2房2廳2衛.", formula: "Raw `v`.", layer: "rent-clean", origin: "site", official: true },
  { field: "floor", label: "樓層 (floor)", unit: "", definition: "Floor / total floors, e.g. 八層/九層.", formula: "Raw `f`.", layer: "rent-clean", origin: "site", official: true },
  { field: "hasMgmtOrg", label: "有無管理組織 (mgmt org)", unit: "boolean", definition: "Whether the building has a management organisation. CONFOUND WARNING for premium analysis: mgmt-org/elevator strongly correlate with building age and unit size, and small old units run HIGHER per-坪 — a naive with/without cut can show a reversed 'premium'. Control for age and area (or compare within rentKind + size bands) first.", formula: "Raw `m` === 有.", layer: "rent-clean", origin: "normalized", official: true },
  { field: "hasFurniture", label: "有無附傢俱 (furniture)", unit: "boolean", definition: "Whether the lease includes furniture. Era-consistent: old form reports a flag, new form lists 傢俱 among equipment.", formula: "Raw `fn` === 有 (old form), or 傢俱 in the `fn` equipment list (new form).", layer: "rent-clean", origin: "normalized", official: true },
  { field: "hasElevator", label: "有無電梯 (elevator)", unit: "boolean|null", definition: "Whether the building has an elevator. New-form rows (簽約 ≥112/09) only; null = unreported (all old-form rows). Same confound warning as hasMgmtOrg: correlates with age/size — control before quoting an elevator premium.", formula: "Raw `el` (有→true, 無→false, ''→null).", layer: "rent-clean", origin: "normalized", official: true },
  { field: "equipment", label: "附屬設備 (equipment)", unit: "", definition: "Comma list of included equipment (冷氣、熱水器、洗衣機、傢俱…). New-form rows only; '' on old-form rows.", formula: "Raw `fn` when it is a list (new form).", layer: "rent-clean", origin: "site", official: true },
  { field: "rentalType", label: "出租型態 (rental type)", unit: "", definition: "Reported 出租型態 — one of: 整戶出租, 分層出租, 獨立套房, 分租套房, 分租雅房; '' when unreported (all old-form rows, ~15% of new-form). The authoritative segmentation field when present; rentKind is the era-stable coarse rollup.", formula: "Raw `rtype`.", layer: "rent-clean", origin: "site", official: true },
  { field: "rentalService", label: "租賃住宅服務 (rental service)", unit: "", definition: "Rental-service-business involvement — one of: 一般轉租, 一般代管, 一般包租, 社會住宅代管, 社會住宅包租轉租; '' = none. 社會住宅* leases are SUBSIDIZED social housing (below-market rent) — segment them out for market-rate comps. NOTE this cut OVERLAPS rentKind=套房 (a subsidized lease can be a studio/room); for MECE segment shares peel off 社會住宅* first, then 套房 from the remainder. ERA WARNING: essentially unlabeled on pre-2023-09 (old-form) rows — you cannot strip subsidized leases from a 2022-2023H1 baseline, so cross-seam 'market rent' trends overstate the rise; prefer within-era trends.", formula: "Raw `rserviec` (sic, site key).", layer: "rent-clean", origin: "site", official: true },
  { field: "buildingAgeYears", label: "屋齡 (building age)", unit: "年", definition: "Building age in years from raw `g`; 0 frequently denotes 'unreported', null when the field is blank.", formula: "Raw `g` (inferred field; treat 0 with care).", layer: "rent-clean", origin: "inferred", official: false },
  { field: "rentPeriod", label: "租賃期間 (lease period)", unit: "", definition: "ROC start~end, e.g. 1150505~1200504; '' when unreported. ~100% filled on new-form rows (簽約 ≥112/09), ~0% on old-form.", formula: "Raw `rperiod`.", layer: "rent-clean", origin: "site", official: true },
  { field: "note", label: "備註 (note)", unit: "", definition: "Remarks; exclusion signals (親友/含車位/含管理費…) live here.", formula: "Raw `note`.", layer: "rent-clean", origin: "site", official: true },
  { field: "lat", label: "緯度 (lat)", unit: "°", definition: "Latitude.", layer: "rent-clean", origin: "site", official: false },
  { field: "lon", label: "經度 (lon)", unit: "°", definition: "Longitude.", layer: "rent-clean", origin: "site", official: false },
  { field: "detailKey", label: "明細鍵 (detail key)", unit: "", definition: "Opaque key for an optional per-record detail fetch.", formula: "Raw `sq`.", layer: "rent-clean", origin: "site", official: false },

  // ── RENT (租賃) — Refined Rent Record (--rent --refine). ───────────────────
  { field: "netRentTwd", label: "淨月租金 (net rent)", unit: "TWD/月", definition: "Monthly rent minus separately reported car-park rent.", formula: "月租金 − 車位租金 (when reported separately).", layer: "rent-refined", origin: "computed", official: false },
  { field: "netAreaPing", label: "淨面積 (net area)", unit: "坪", definition: "Area net of parking; equals areaPing (parking area is never reported for rent).", formula: "= areaPing (parking area unreported for rent).", layer: "rent-refined", origin: "computed", official: false },
  { field: "adjUnitRentTwdPing", label: "調整後單價 (adj unit rent)", unit: "TWD/坪/月", definition: "Corrected rent per 坪; recomputed from net rent when a car-park rent was subtracted.", formula: "site `p`, else netRent/area.", layer: "rent-refined", origin: "computed", official: false },
  { field: "rentKind", label: "出租型態(概略) (rent kind)", unit: "", definition: "Coarse 出租型態 — exactly one of: 整棟/獨立, 套房, 分層/其他, 車位, 土地. Uses reported rentalType when present (獨立套房/分租套房/分租雅房 → 套房; 整戶出租/分層出租 → 分層/其他 — NOTE 整戶出租 means a whole UNIT/flat, so it lands in 分層/其他; 整棟/獨立 is reserved for whole-building/detached 透天/農舍), else proxied from 標的+建物型態 (old-form rows). Segment 套房 out before taking district medians (different market); use rentalType for exact 型態.", formula: "From rentalType, else 標的 + 建物型態.", layer: "rent-refined", origin: "inferred", official: false },
  { field: "excluded", label: "排除 (excluded)", unit: "boolean", definition: "Flagged out of residential comps (never dropped).", formula: "親友 / 純車位 / 非住宅 (主要用途 lacks 住, or commercial 建物型態: 店面/辦公商業/廠辦/工廠/倉庫).", layer: "rent-refined", origin: "inferred", official: false },
  { field: "excludeReason", label: "排除原因 (exclude reason)", unit: "", definition: "Reason a lease was flagged out of comps. 非住宅 covers both non-住 主要用途 and commercial 建物型態.", formula: "親友交易 | 純車位 | 非住宅 | ''.", layer: "rent-refined", origin: "inferred", official: false },
  { field: "parkRentIncluded", label: "車位租金含於總額 (park rent bundled)", unit: "boolean", definition: "Parking present but its rent is bundled into the total.", formula: "標的 has 車位, 標的 ≠ 車位, 車位租金 = 0.", layer: "rent-refined", origin: "inferred", official: false },
  { field: "confidence", label: "信心度 (confidence)", unit: "", definition: "Rollup confidence; degrades for exclusions, bundled parking, and inferred age.", formula: "high | medium | low.", layer: "rent-refined", origin: "inferred", official: false },
];

/** All clean-layer field names, in declaration order. */
export const CLEAN_FIELDS: string[] = GLOSSARY.filter((g) => g.layer === "clean").map((g) => g.field);

/** All refined-layer field names, in declaration order. */
export const REFINED_FIELDS: string[] = GLOSSARY.filter((g) => g.layer === "refined").map((g) => g.field);
